services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: Database-container
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TEMse-2024LMC
    ports: 
      - "1433:1433"
    networks:
      - ec-network
    volumes: 
      - sqlserverdata:/var/opt/mssql

  database_init:
    container_name: DatabaseInit-container
    depends_on:
      - sqlserver
    networks:
      - ec-network
    restart: on-failure
    build:
      context: .
      dockerfile: DatabaseInitializer/Dockerfile

  parserdata:
    container_name: Parserdata-container
    depends_on:
      - sqlserver
    networks:
      - ec-network
    restart: on-failure
    build:
      context: .
      dockerfile: ParserData/Dockerfile

  connector:
    container_name: Connector-container
    depends_on:
      - sqlserver
    networks:
      - ec-network
    build:
      context: .
      dockerfile: Connector/Dockerfile
    volumes:
      - ./EnergyConsumptionData:/app/EnergyConsumptionData/SpainData
      - ./EnergyConsumptionData:/app/EnergyConsumptionData/RegionData

  scheduler:
    image: alpine
    container_name: Scheduler-container
    networks:
      - ec-network
    entrypoint: ["/bin/sh", "-c", "crond -f"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    build:
      context: .
      dockerfile: Scheduler/Dockerfile

networks:
  ec-network:
    driver: bridge

volumes:
  sqlserverdata: