services:
  parserdata:
    build:
      context: .
      dockerfile: ParserData/Dockerfile
    volumes:
      - ./ParserData/appsettings.json:/app/appsettings.json  # Mapea el archivo appsettings.json
    ports:
      - "5000:5000"

  connector:
    build:
      context: .
      dockerfile: Connector/Dockerfile
    volumes:
      - C:/EnergyConsumption_Data:/app/EnergyConsumption_Data
      - ./Connector/appsettings.json:/app/appsettings.json  # Mapea el archivo appsettings.json
    ports:
      - "5001:5001"

